In [2]:
import numpy as np

In [3]:
my_list = [2, 3, 4]

In [4]:
array_from_list = np.array(my_list)

In [5]:
print(array_from_list)

[2 3 4]


In [6]:
range_array = np.arange(10)  # Creates an array from 0 to 9

In [7]:
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
linspace_array = np.linspace(0, 10, 10)  # Creates 11 numbers from 0 to 1

In [9]:
print(linspace_array)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [10]:
#multi-dimensional arrays
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[:, 0]  # Gets the first column

In [11]:
print(first_row, first_col)

[2 3 4] [2 4]


In [22]:
np.random.seed(10)  # Set the seed
random_array = np.random.rand(1)  # Generates random numbers between 0 and 1
print(random_array*10)

[7.71320643]


In [25]:
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))
print(random_integers)

[[ 6 85]
 [22 11]
 [12 92]
 [96 62]
 [57 79]]


In [27]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
print(arr1, arr2)
result1 = arr1 + arr2  # Element-wise addition
result2 = arr1 / arr2  # Element-wise division
print(result1, result2)

[1. 1. 1. 1.] [3 3 3 3]
[4. 4. 4. 4.] [0.33333333 0.33333333 0.33333333 0.33333333]


In [33]:
arr3 = [3, 4, 5, 6, 3, 2, 1]
arr = np.array(arr3) #need to convert it into a numpy array so that, conditions would work. 
selected_elements = arr[arr > 3]
print(selected_elements)

[4 5 6]


In [35]:
arr11 = np.array([[1, 2], [3, 4]])
arr12 = np.array([[5, 6], [7, 8]])
result = arr11 + arr12
print (result)
result = arr11 * arr12
print (result)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
